name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.6
  - jupyter
  - jupyterlab=3.0.13
  - seaborn=0.11.1
  - Jinja2=2.11.3
  - pandas==1.1.5
  - pip=20.3.3
  - pandas-profiling==2.13.0
  - pyarrow=2.0
  - pip:
      - wandb==0.10.31